<h3>Reshaping Arrays</h3>

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


<h3>Slicing(Selecting parts of arrays)</h3>

In [4]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])
print(arr[:3])
print(arr[-2:])

[20 30 40]
[10 20 30]
[50 60]


In [5]:
# for 2D arrays

arr=np.array([[1,2,3],[4,5,6],[8,9,0]])
print(arr[0,1])
print(arr[1,:])
print(arr[:,2])

2
[4 5 6]
[3 6 0]


In [9]:
#Broadcasting

arr=np.array([1,2,3,4])
print(arr+10)
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix+5)
print(matrix+np.array([10,20,30]))

[11 12 13 14]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [17]:
print("Original")
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print("Second row:",arr[1,:])
print("After adding 5 to last Column:")
arr[:, -1] = arr[:, -1] + 5
print(arr)

Original
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Second row: [5 6 7 8]
After adding 5 to last Column:
[[ 1  2  3  9]
 [ 5  6  7 13]
 [ 9 10 11 17]]
